# Generated by Django 5.1.7 on 2025-05-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='storage_limit_gb',
        ),
    ]
