# Generated by Django 5.1.7 on 2025-05-23 16:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('10'), max_digits=19),
        ),
    ]
