# Generated by Django 5.1.7 on 2025-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('inventory', '0002_inventory_low_stock_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('store_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productunit',
            unique_together={('store_id', 'name')},
        ),
    ]
