# Generated by Django 5.1.7 on 2025-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store_id', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentmode',
            unique_together={('store_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('store_id', 'email')},
        ),
    ]
