# Generated by Django 5.1.7 on 2025-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchase_tax_alter_sale_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='item_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_sale_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
