# Generated by Django 5.1.7 on 2025-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('stock_manager', 'Stock Manager'), ('sales', 'Sales')], max_length=20),
        ),
    ]
