# Generated by Django 5.1.7 on 2025-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_store',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
