# Generated by Django 5.1.7 on 2025-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothings', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('store_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('store_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('store_id', 'name')},
        ),
    ]
